import { VaultRepository } from '../repositories/vault.repository';
import { StorageService } from './storage.service';
import { NotFoundError, BusinessError } from '../utils/errors';
import { cache } from '../config/redis';
import { CACHE_KEYS, CACHE_TTL } from '../constants';
import { VaultFolderTree, PaginationQuery } from '../types';
import slugify from 'slugify';
import { prisma } from '../config/database';

const vaultRepo = new VaultRepository();
const storageService = new StorageService();

export class VaultService {
  async getFolderTree(userId: string): Promise<VaultFolderTree[]> {
    const cached = await cache.get<VaultFolderTree[]>(CACHE_KEYS.VAULT_FOLDERS(userId));
    if (cached) return cached;

    const folders = await vaultRepo.findFoldersByUserId(userId);
    const docCounts = await vaultRepo.getDocumentCountByFolder(userId);

    const buildTree = (parentId: string | null): VaultFolderTree[] =>
      folders
        .filter((f) => (f.parentId ?? null) === parentId)
        .map((f) => ({
          id: f.id, name: f.name, slug: f.slug, icon: f.icon, color: f.color,
          isSystem: f.isSystem, documentCount: docCounts[f.id] ?? 0,
          children: buildTree(f.id),
        }));

    const tree = buildTree(null);
    await cache.set(CACHE_KEYS.VAULT_FOLDERS(userId), tree, CACHE_TTL.MEDIUM);
    return tree;
  }

  async createFolder(userId: string, dto: {
    name: string; parentId?: string | null; description?: string; color?: string; icon?: string;
  }) {
    const slug = slugify(dto.name, { lower: true, strict: true });
    const existing = await vaultRepo.findFolderBySlug(slug, userId, dto.parentId);
    if (existing) throw new BusinessError('A folder with this name already exists');
    if (dto.parentId) {
      const parent = await vaultRepo.findFolderById(dto.parentId, userId);
      if (!parent) throw new NotFoundError('Parent folder');
    }
    const folder = await vaultRepo.createFolder({
      user: { connect: { id: userId } },
      name: dto.name, slug,
      description: dto.description,
      color: dto.color, icon: dto.icon,
      ...(dto.parentId ? { parent: { connect: { id: dto.parentId } } } : {}),
      isSystem: false,
    });
    await cache.del(CACHE_KEYS.VAULT_FOLDERS(userId));
    return folder;
  }

  async updateFolder(id: string, userId: string, data: Partial<{ name: string; color: string; icon: string }>) {
    const folder = await vaultRepo.findFolderById(id, userId);
    if (!folder) throw new NotFoundError('Folder');
    if (folder.isSystem) throw new BusinessError('System folders cannot be modified');
    const updated = await vaultRepo.updateFolder(id, data);
    await cache.del(CACHE_KEYS.VAULT_FOLDERS(userId));
    return updated;
  }

  async deleteFolder(id: string, userId: string): Promise<void> {
    const folder = await vaultRepo.findFolderById(id, userId);
    if (!folder) throw new NotFoundError('Folder');
    if (folder.isSystem) throw new BusinessError('System folders cannot be deleted');
    await vaultRepo.deleteFolder(id, userId);
    await cache.del(CACHE_KEYS.VAULT_FOLDERS(userId));
  }

  async uploadDocument(userId: string, file: Express.Multer.File, dto: {
    folderId?: string; name: string; description?: string;
    category: string; tags?: string[]; metadata?: Record<string, unknown>;
  }) {
    if (dto.folderId) {
      const folder = await vaultRepo.findFolderById(dto.folderId, userId);
      if (!folder) throw new NotFoundError('Folder');
    }
    const stored = await storageService.store({
      userId, category: dto.category,
      originalName: file.originalname,
      buffer: file.buffer, mimeType: file.mimetype,
    });
    const doc = await vaultRepo.createDocument({
      user: { connect: { id: userId } },
      ...(dto.folderId ? { folder: { connect: { id: dto.folderId } } } : {}),
      name: dto.name, description: dto.description, category: dto.category,
      fileName: stored.fileName, fileKey: stored.fileKey, fileUrl: stored.fileUrl,
      mimeType: stored.mimeType, fileSizeBytes: stored.fileSizeBytes,
      checksum: stored.checksum,
      tags: JSON.stringify(dto.tags ?? []),
      metadata: dto.metadata ? JSON.stringify(dto.metadata) : null,
      isAutoGenerated: false,
    } as any);
    await cache.del(CACHE_KEYS.VAULT_FOLDERS(userId));
    return doc;
  }

  async getDocuments(userId: string, folderId?: string) {
    if (folderId) {
      const folder = await vaultRepo.findFolderById(folderId, userId);
      if (!folder) throw new NotFoundError('Folder');
      return vaultRepo.findDocumentsByFolder(folderId, userId);
    }
    return vaultRepo.searchDocuments(userId, '', {}, { page: 1, pageSize: 100 });
  }

  async getDocument(id: string, userId: string) {
    const doc = await vaultRepo.findDocumentById(id, userId);
    if (!doc) throw new NotFoundError('Document');
    return this.parseDocumentJson(doc);
  }

  async downloadDocument(id: string, userId: string) {
    const doc = await vaultRepo.findDocumentById(id, userId);
    if (!doc) throw new NotFoundError('Document');
    await vaultRepo.incrementDownloadCount(id);
    const fileBuffer = await storageService.retrieve(doc.fileKey);
    return { doc: this.parseDocumentJson(doc), buffer: fileBuffer };
  }

  async deleteDocument(id: string, userId: string): Promise<void> {
    const doc = await vaultRepo.findDocumentById(id, userId);
    if (!doc) throw new NotFoundError('Document');
    if (doc.isAutoGenerated) throw new BusinessError('Auto-generated documents cannot be deleted');
    await Promise.all([vaultRepo.softDeleteDocument(id, userId), storageService.delete(doc.fileKey)]);
  }

  async searchDocuments(userId: string, query: string, filters: any, pagination: PaginationQuery) {
    return vaultRepo.searchDocuments(userId, query, filters, pagination);
  }

  async autoCreateFromTransaction(userId: string, transactionId: string, merchantName: string, amount: number) {
    const receiptsFolder = await vaultRepo.findFolderBySlug('receipts', userId, null);
    if (!receiptsFolder) return;
    await vaultRepo.createDocument({
      user: { connect: { id: userId } },
      folder: { connect: { id: receiptsFolder.id } },
      name: `${merchantName} — Receipt`,
      category: 'RECEIPT',
      fileName: `receipt_${transactionId}.pdf`,
      fileKey: `receipts/${userId}/${transactionId}.pdf`,
      mimeType: 'application/pdf',
      fileSizeBytes: 0,
      tags: JSON.stringify(['auto-generated', 'receipt']),
      metadata: JSON.stringify({ transactionId, merchantName, amount }),
      isAutoGenerated: true,
    } as any);
  }

  // Parse JSON string fields back to objects for API response
  private parseDocumentJson(doc: any) {
    try { doc.tags = JSON.parse(doc.tags ?? '[]'); } catch {}
    try { if (doc.metadata) doc.metadata = JSON.parse(doc.metadata); } catch {}
    return doc;
  }
}
