import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcrypt';
import { v4 as uuidv4 } from 'uuid';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding demo data...');

  // 1. Create a demo user
  const hashedPassword = await bcrypt.hash('password123', 10);
  
  const user = await prisma.user.upsert({
    where: { email: 'demo@sbi.com' },
    update: {},
    create: {
      id: 'demo-user-123',
      customerId: 'CIF' + Math.floor(Math.random() * 10000000),
      firstName: 'Lavish',
      lastName: 'Sharma',
      email: 'demo@sbi.com',
      phone: '+919876543210',
      passwordHash: hashedPassword,
      isActive: true,
    },
  });

  console.log(`Demo user created/found: ${user.id}`);

  // 2. Clear existing demo applications to keep it clean
  await prisma.application.deleteMany({
    where: { userId: user.id }
  });

  // 3. Create a draft "Home Loan" application
  const steps = [
    { name: 'Personal Details', fields: ['firstName', 'lastName', 'dob', 'pan', 'aadhar'] },
    { name: 'Employment Details', fields: ['employerName', 'employmentType', 'monthlyIncome', 'workExperience'] },
    { name: 'Loan Details', fields: ['loanAmount', 'tenure', 'purpose', 'propertyAddress'] },
    { name: 'Document Upload', fields: ['salarySlip', 'bankStatement', 'idProof', 'addressProof'] },
    { name: 'Review & Submit', fields: ['termsAccepted', 'declarationAccepted'] },
  ];

  const allFields = steps.flatMap((s) => s.fields);
  const completedFields = ['firstName', 'lastName', 'dob', 'pan', 'aadhar', 'employerName', 'employmentType', 'monthlyIncome'];
  const missingFields = allFields.filter(f => !completedFields.includes(f));
  
  const formData = {
    firstName: 'Lavish',
    lastName: 'Sharma',
    dob: '1995-08-15',
    pan: 'ABCPS1234F',
    aadhar: '1234 5678 9012',
    employerName: 'Infosys Limited',
    employmentType: 'Salaried',
    monthlyIncome: '85000'
  };

  await prisma.application.create({
    data: {
      id: uuidv4(),
      userId: user.id,
      applicationType: 'LOAN',
      status: 'DRAFT',
      title: 'Home Loan Application',
      currentStep: 2, // User is on step 3 (index 2)
      totalSteps: 5,
      completionPercent: 44, // 8 / 18 fields
      estimatedMinutes: 15,
      formData: JSON.stringify(formData),
      completedFields: JSON.stringify(completedFields),
      missingFields: JSON.stringify(missingFields),
      steps: JSON.stringify(steps),
      expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    }
  });

  console.log('Draft application seeded.');

  // 4. Create Vault Folders and Documents (Smart Vault Demo)
  // Clear existing folders for demo user
  await prisma.vaultFolder.deleteMany({ where: { userId: user.id } });

  const acFolder = await prisma.vaultFolder.create({
    data: {
      id: uuidv4(),
      userId: user.id,
      name: 'Samsung AC Purchase',
      slug: 'samsung-ac-purchase',
      description: 'Auto-created from transaction',
      color: '#003399',
      icon: 'shopping-bag',
      isSystem: false,
    }
  });

  // Seed transaction to link it
  const transactionId = uuidv4();
  
  // Seed documents into the folder
  await prisma.document.createMany({
    data: [
      {
        id: uuidv4(),
        userId: user.id,
        folderId: acFolder.id,
        category: 'RECEIPT',
        name: 'Samsung AC - Payment Receipt',
        fileKey: 'demo/receipt.pdf',
        fileName: 'receipt_samsung.pdf',
        mimeType: 'application/pdf',
        fileSizeBytes: 15400,
        isAutoGenerated: true,
        tags: JSON.stringify(['samsung', 'ac', 'receipt']),
      },
      {
        id: uuidv4(),
        userId: user.id,
        folderId: acFolder.id,
        category: 'GST_BILL',
        name: 'Samsung AC - GST Invoice',
        fileKey: 'demo/invoice.pdf',
        fileName: 'invoice_samsung.pdf',
        mimeType: 'application/pdf',
        fileSizeBytes: 24500,
        isAutoGenerated: true,
        tags: JSON.stringify(['samsung', 'ac', 'invoice', 'tax']),
      },
      {
        id: uuidv4(),
        userId: user.id,
        folderId: acFolder.id,
        category: 'WARRANTY',
        name: 'Samsung AC - Warranty Card',
        fileKey: 'demo/warranty.pdf',
        fileName: 'warranty_samsung.pdf',
        mimeType: 'application/pdf',
        fileSizeBytes: 12000,
        isAutoGenerated: true,
        tags: JSON.stringify(['samsung', 'ac', 'warranty']),
        metadata: JSON.stringify({ 
          supportNumber: '1800-40-SAMSUNG',
          warrantyEnds: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString()
        })
      }
    ]
  });

  console.log('Smart Vault documents seeded.');
  console.log('Seed completed successfully!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
