// ─── Dummy Data for YONO Smart Companion ───────────────────────────────────

export const user = {
  name: "Lavish Sharma",
  firstName: "Lavish",
  accountNumber: "XXXX XXXX 4821",
  ifsc: "SBIN0001234",
  branch: "Connaught Place, New Delhi",
  customerId: "CIF7823419",
  email: "lavish.sharma@email.com",
  phone: "+91 98765 43210",
  pan: "ABCPS1234F",
  aadhar: "XXXX XXXX 7890",
  rewardPoints: 12840,
  kycStatus: "Verified",
  avatar: null,
};

export const accounts = [
  {
    id: "acc1",
    type: "Savings Account",
    number: "XXXX XXXX 4821",
    balance: 284350.75,
    availableBalance: 280000,
    ifsc: "SBIN0001234",
    branch: "Connaught Place, New Delhi",
    status: "Active",
    interestRate: 3.5,
    lastTransaction: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: "acc2",
    type: "Current Account",
    number: "XXXX XXXX 9302",
    balance: 1250000,
    availableBalance: 1250000,
    ifsc: "SBIN0001234",
    branch: "Connaught Place, New Delhi",
    status: "Active",
    interestRate: 0,
    lastTransaction: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
];

export const transactions = [
  {
    id: "t1",
    type: "credit",
    amount: 85000,
    description: "Salary — Infosys Ltd",
    category: "Income",
    date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    merchant: "Infosys Limited",
    location: "Bangalore, KA",
    paymentMethod: "NEFT",
    ref: "NEFT2024060112345",
    icon: "salary",
  },
  {
    id: "t2",
    type: "debit",
    amount: 22000,
    description: "Rent — Sunshine Apartments",
    category: "Housing",
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    merchant: "Sunshine Apartments",
    location: "New Delhi",
    paymentMethod: "UPI",
    ref: "UPI24060298765",
    icon: "home",
  },
  {
    id: "t3",
    type: "debit",
    amount: 3240,
    description: "Zomato — Food Delivery",
    category: "Food",
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    merchant: "Zomato India",
    location: "New Delhi",
    paymentMethod: "UPI",
    ref: "UPI24060311111",
    icon: "food",
  },
  {
    id: "t4",
    type: "debit",
    amount: 15499,
    description: "Amazon — Electronics",
    category: "Shopping",
    date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    merchant: "Amazon India",
    location: "Online",
    paymentMethod: "Debit Card",
    ref: "DC2024060488888",
    icon: "shopping",
  },
  {
    id: "t5",
    type: "debit",
    amount: 18500,
    description: "Home Loan EMI",
    category: "Loan EMI",
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    merchant: "SBI Home Loans",
    location: "Auto Debit",
    paymentMethod: "Auto Debit",
    ref: "AD2024060577777",
    icon: "loan",
  },
  {
    id: "t6",
    type: "debit",
    amount: 2199,
    description: "Ola — Cab Rides",
    category: "Travel",
    date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    merchant: "Ola Cabs",
    location: "New Delhi",
    paymentMethod: "UPI",
    ref: "UPI24060666666",
    icon: "travel",
  },
  {
    id: "t7",
    type: "credit",
    amount: 5000,
    description: "Cashback — SBI ELITE Card",
    category: "Rewards",
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    merchant: "SBI Rewards",
    location: "Auto Credit",
    paymentMethod: "Auto Credit",
    ref: "RWRD2024060555555",
    icon: "reward",
  },
  {
    id: "t8",
    type: "debit",
    amount: 5000,
    description: "SIP — Axis Bluechip Fund",
    category: "Investment",
    date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    merchant: "SBI MF",
    location: "Auto Debit",
    paymentMethod: "Auto Debit",
    ref: "SIP2024060444444",
    icon: "investment",
  },
  {
    id: "t9",
    type: "debit",
    amount: 1499,
    description: "Netflix — Subscription",
    category: "Entertainment",
    date: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
    merchant: "Netflix India",
    location: "Online",
    paymentMethod: "Credit Card",
    ref: "CC2024060333333",
    icon: "entertainment",
  },
  {
    id: "t10",
    type: "debit",
    amount: 4200,
    description: "BSES — Electricity Bill",
    category: "Utilities",
    date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    merchant: "BSES Yamuna Power",
    location: "New Delhi",
    paymentMethod: "UPI",
    ref: "UPI2024060222222",
    icon: "utility",
  },
];

export const cards = [
  {
    id: "card1",
    type: "debit",
    name: "SBI Classic Debit Card",
    number: "4523 XXXX XXXX 8821",
    holder: "LAVISH SHARMA",
    expiry: "12/27",
    cvv: "***",
    network: "Visa",
    status: "Active",
    limit: 100000,
    used: 0,
    color: "#003399",
    cashbackEarned: 0,
    offers: ["10% off on Flipkart", "5% off on BigBazaar"],
  },
  {
    id: "card2",
    type: "credit",
    name: "SBI ELITE Credit Card",
    number: "5214 XXXX XXXX 3301",
    holder: "LAVISH SHARMA",
    expiry: "08/28",
    cvv: "***",
    network: "Mastercard",
    status: "Active",
    limit: 500000,
    used: 87430,
    color: "#0d1b3e",
    cashbackEarned: 12840,
    offers: ["2X rewards on travel", "Lounge access", "1% fuel surcharge waiver"],
  },
];

export const loans = [
  {
    id: "loan1",
    type: "Home Loan",
    bank: "SBI",
    accountNumber: "HL202401234",
    principal: 5000000,
    outstanding: 4234500,
    emi: 44250,
    interestRate: 8.5,
    tenure: 240,
    tenureRemaining: 192,
    nextEmiDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
    status: "Active",
    progress: 15,
    disbursementDate: new Date("2024-01-15"),
  },
  {
    id: "loan2",
    type: "Car Loan",
    bank: "SBI",
    accountNumber: "CL202312345",
    principal: 800000,
    outstanding: 520000,
    emi: 15800,
    interestRate: 9.2,
    tenure: 60,
    tenureRemaining: 35,
    nextEmiDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
    status: "Active",
    progress: 35,
    disbursementDate: new Date("2023-12-01"),
  },
];

export const investments = {
  mutualFunds: [
    {
      id: "mf1",
      name: "SBI Blue Chip Fund",
      category: "Large Cap",
      nav: 78.45,
      units: 234.56,
      invested: 150000,
      currentValue: 184103,
      returns: 22.7,
      sipAmount: 5000,
      folioNumber: "SBI/2022/234567",
      rating: 5,
    },
    {
      id: "mf2",
      name: "SBI Small Cap Fund",
      category: "Small Cap",
      nav: 142.30,
      units: 88.12,
      invested: 100000,
      currentValue: 125419,
      returns: 25.4,
      sipAmount: 3000,
      folioNumber: "SBI/2022/345678",
      rating: 4,
    },
    {
      id: "mf3",
      name: "SBI Liquid Fund",
      category: "Liquid",
      nav: 3842.55,
      units: 13.02,
      invested: 50000,
      currentValue: 50034,
      returns: 7.2,
      sipAmount: 0,
      folioNumber: "SBI/2023/456789",
      rating: 4,
    },
  ],
  fds: [
    {
      id: "fd1",
      principal: 200000,
      rate: 7.1,
      tenure: 365,
      maturityDate: new Date("2025-06-01"),
      maturityAmount: 214200,
      startDate: new Date("2024-06-01"),
      status: "Active",
      type: "Regular FD",
      accountNumber: "FD20240601001",
    },
    {
      id: "fd2",
      principal: 500000,
      rate: 7.25,
      tenure: 730,
      maturityDate: new Date("2026-03-15"),
      maturityAmount: 576250,
      startDate: new Date("2024-03-15"),
      status: "Active",
      type: "Tax Saver FD",
      accountNumber: "FD20240315002",
    },
  ],
  rds: [
    {
      id: "rd1",
      monthlyInstallment: 10000,
      rate: 6.8,
      tenure: 24,
      completedMonths: 8,
      maturityDate: new Date("2026-02-01"),
      status: "Active",
      accountNumber: "RD20240201001",
    },
  ],
};

export const insurance = [
  {
    id: "ins1",
    type: "Life Insurance",
    company: "LIC of India",
    policyNumber: "LIC245678901",
    sumAssured: 10000000,
    premium: 28000,
    premiumFrequency: "Annual",
    nextDueDate: new Date("2025-04-01"),
    status: "Active",
    maturityYear: 2040,
    coverageDetails: "Term Life Cover",
  },
  {
    id: "ins2",
    type: "Health Insurance",
    company: "SBI General Insurance",
    policyNumber: "SBI-H-2023-456789",
    sumAssured: 500000,
    premium: 12500,
    premiumFrequency: "Annual",
    nextDueDate: new Date("2025-07-15"),
    status: "Active",
    maturityYear: null,
    coverageDetails: "Family Floater — 4 members",
  },
  {
    id: "ins3",
    type: "Vehicle Insurance",
    company: "SBI General Insurance",
    policyNumber: "SBI-V-2024-112233",
    sumAssured: 800000,
    premium: 18500,
    premiumFrequency: "Annual",
    nextDueDate: new Date("2025-01-20"),
    status: "Active",
    maturityYear: null,
    coverageDetails: "Comprehensive — Honda City",
  },
];

export const upcomingBills = [
  { id: "b1", name: "Electricity — BSES", amount: 4200, dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000), category: "Utility", status: "Due Soon" },
  { id: "b2", name: "Internet — Airtel", amount: 999, dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000), category: "Utility", status: "Due Soon" },
  { id: "b3", name: "OTT Bundle", amount: 1498, dueDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000), category: "Entertainment", status: "Upcoming" },
  { id: "b4", name: "Home Loan EMI", amount: 44250, dueDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000), category: "Loan", status: "Upcoming" },
  { id: "b5", name: "Car Loan EMI", amount: 15800, dueDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000), category: "Loan", status: "Upcoming" },
  { id: "b6", name: "LIC Premium", amount: 28000, dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000), category: "Insurance", status: "Upcoming" },
];

export const beneficiaries = [
  { id: "ben1", name: "Priya Sharma", bank: "HDFC Bank", accountNumber: "XXXX4567", upiId: "priya@hdfc", initials: "PS", color: "#7c3aed" },
  { id: "ben2", name: "Rahul Verma", bank: "ICICI Bank", accountNumber: "XXXX8901", upiId: "rahul@icici", initials: "RV", color: "#0891b2" },
  { id: "ben3", name: "Mom", bank: "SBI", accountNumber: "XXXX1234", upiId: "mom@sbi", initials: "M", color: "#dc2626" },
  { id: "ben4", name: "Vikram Singh", bank: "Axis Bank", accountNumber: "XXXX5678", upiId: "vikram@axis", initials: "VS", color: "#059669" },
  { id: "ben5", name: "Neha Gupta", bank: "Kotak Bank", accountNumber: "XXXX2345", upiId: "neha@kotak", initials: "NG", color: "#d97706" },
];

export const monthlySpendData = [
  { month: "Jan", spend: 52000, income: 85000, savings: 33000 },
  { month: "Feb", spend: 48000, income: 85000, savings: 37000 },
  { month: "Mar", spend: 61000, income: 90000, savings: 29000 },
  { month: "Apr", spend: 55000, income: 85000, savings: 30000 },
  { month: "May", spend: 67000, income: 95000, savings: 28000 },
  { month: "Jun", spend: 71230, income: 85000, savings: 13770 },
];

export const categorySpend = [
  { name: "Housing", value: 22000, color: "#003399" },
  { name: "Food", value: 8500, color: "#0099cc" },
  { name: "Shopping", value: 15499, color: "#6366f1" },
  { name: "Travel", value: 4200, color: "#8b5cf6" },
  { name: "Utilities", value: 6400, color: "#06b6d4" },
  { name: "Entertainment", value: 2500, color: "#84cc16" },
  { name: "Investment", value: 8000, color: "#10b981" },
  { name: "Loan EMI", value: 18500, color: "#f59e0b" },
];

export const smartVaultDocuments = [
  {
    id: "doc1",
    name: "Account Statement — June 2024",
    type: "Statement",
    category: "Statements",
    date: new Date("2024-06-30"),
    size: "284 KB",
    merchant: "SBI Bank",
    fileType: "PDF",
    preview: true,
  },
  {
    id: "doc2",
    name: "FD Certificate — ₹2L",
    type: "Certificate",
    category: "FD Certificates",
    date: new Date("2024-06-01"),
    size: "128 KB",
    merchant: "SBI Fixed Deposits",
    fileType: "PDF",
    preview: true,
  },
  {
    id: "doc3",
    name: "Home Loan Statement",
    type: "Loan Document",
    category: "Loan Documents",
    date: new Date("2024-05-31"),
    size: "512 KB",
    merchant: "SBI Home Loans",
    fileType: "PDF",
    preview: true,
  },
  {
    id: "doc4",
    name: "LIC Policy Document",
    type: "Insurance",
    category: "Insurance",
    date: new Date("2024-04-01"),
    size: "1.2 MB",
    merchant: "LIC of India",
    fileType: "PDF",
    preview: true,
  },
  {
    id: "doc5",
    name: "Form 26AS — FY 2023-24",
    type: "Tax Document",
    category: "Tax Documents",
    date: new Date("2024-06-15"),
    size: "340 KB",
    merchant: "Income Tax Dept.",
    fileType: "PDF",
    preview: true,
  },
  {
    id: "doc6",
    name: "Samsung TV — Invoice",
    type: "Receipt",
    category: "Receipts",
    date: new Date("2024-05-12"),
    size: "180 KB",
    merchant: "Samsung India",
    fileType: "PDF",
    preview: true,
    metadata: {
      amount: 72990,
      warranty: "2 Years",
      supportNumber: "1800-407-7355",
      returnWindow: "30 Days",
      serialNumber: "SN2024051200234",
    },
  },
  {
    id: "doc7",
    name: "Mutual Fund Statement",
    type: "Investment",
    category: "Statements",
    date: new Date("2024-05-31"),
    size: "220 KB",
    merchant: "SBI Mutual Fund",
    fileType: "PDF",
    preview: true,
  },
  {
    id: "doc8",
    name: "GST Invoice — AWS Cloud",
    type: "GST Bill",
    category: "GST Bills",
    date: new Date("2024-06-01"),
    size: "95 KB",
    merchant: "Amazon Web Services",
    fileType: "PDF",
    preview: true,
  },
];

export const resumeApplications = [
  {
    id: "app1",
    type: "Home Loan",
    progress: 82,
    lastEdited: new Date(Date.now() - 3 * 60 * 60 * 1000),
    estimatedRemaining: "8 min",
    steps: ["Personal Details", "Income Details", "Property Details", "Documents", "Review & Submit"],
    currentStep: 3,
    icon: "home",
  },
  {
    id: "app2",
    type: "FD Creation",
    progress: 55,
    lastEdited: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    estimatedRemaining: "3 min",
    steps: ["Select Amount", "Choose Tenure", "Nomination", "Confirm"],
    currentStep: 1,
    icon: "piggy-bank",
  },
  {
    id: "app3",
    type: "Nominee Update",
    progress: 92,
    lastEdited: new Date(Date.now() - 2 * 60 * 60 * 1000),
    estimatedRemaining: "1 min",
    steps: ["Nominee Details", "Relationship", "Upload ID", "Confirm"],
    currentStep: 3,
    icon: "user-check",
  },
  {
    id: "app4",
    type: "Credit Card Application",
    progress: 35,
    lastEdited: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    estimatedRemaining: "12 min",
    steps: ["Basic Info", "Employment", "Income", "Documents", "Review"],
    currentStep: 1,
    icon: "credit-card",
  },
];

export const commandItems = [
  { id: "c1", feature: "Block Debit Card", icon: "shield-off", module: "Cards", time: "30 sec", shortcut: "⌘B", path: "/cards" },
  { id: "c2", feature: "Increase UPI Limit", icon: "trending-up", module: "UPI", time: "1 min", shortcut: "⌘U", path: "/upi" },
  { id: "c3", feature: "Open FD", icon: "piggy-bank", module: "Investments", time: "5 min", shortcut: "⌘F", path: "/investments" },
  { id: "c4", feature: "Download Statement", icon: "download", module: "Accounts", time: "10 sec", shortcut: "⌘S", path: "/accounts" },
  { id: "c5", feature: "Apply Personal Loan", icon: "banknote", module: "Loans", time: "15 min", shortcut: "⌘L", path: "/loans" },
  { id: "c6", feature: "Order Cheque Book", icon: "book", module: "Accounts", time: "2 min", shortcut: "⌘C", path: "/accounts" },
  { id: "c7", feature: "Change Address", icon: "map-pin", module: "Profile", time: "3 min", shortcut: "⌘A", path: "/settings" },
  { id: "c8", feature: "Pay Electricity Bill", icon: "zap", module: "Payments", time: "1 min", shortcut: "⌘E", path: "/payments" },
  { id: "c9", feature: "Transfer Money", icon: "send", module: "Payments", time: "30 sec", shortcut: "⌘T", path: "/payments" },
  { id: "c10", feature: "Check Balance", icon: "wallet", module: "Accounts", time: "5 sec", shortcut: "⌘W", path: "/accounts" },
  { id: "c11", feature: "Start SIP", icon: "trending-up", module: "Investments", time: "8 min", shortcut: "⌘I", path: "/investments" },
  { id: "c12", feature: "Buy Insurance", icon: "shield", module: "Insurance", time: "10 min", shortcut: null, path: "/insurance" },
  { id: "c13", feature: "Set Savings Goal", icon: "target", module: "Investments", time: "2 min", shortcut: null, path: "/investments" },
  { id: "c14", feature: "Report Lost Card", icon: "alert-triangle", module: "Cards", time: "2 min", shortcut: null, path: "/cards" },
  { id: "c15", feature: "Scan & Pay QR", icon: "qr-code", module: "UPI", time: "20 sec", shortcut: "⌘Q", path: "/upi" },
  { id: "c16", feature: "Smart Vault", icon: "shield", module: "Documents", time: "5 sec", shortcut: null, path: "/documents" },
  { id: "c17", feature: "View UPI Receipts", icon: "receipt", module: "Smart Vault", time: "5 sec", shortcut: null, path: "/documents" },
  { id: "c18", feature: "Apply Home Loan", icon: "banknote", module: "Loans", time: "10 min", shortcut: null, path: "/loans/apply" },
];

export const savingsGoals = [
  { id: "sg1", name: "Emergency Fund", target: 300000, current: 184350, deadline: "Dec 2024" },
  { id: "sg2", name: "Europe Trip", target: 200000, current: 68500, deadline: "Jun 2025" },
  { id: "sg3", name: "New Laptop", target: 120000, current: 45000, deadline: "Sep 2024" },
];

export const marketplaceItems = [
  { id: "m1", category: "Travel", name: "Air India — Delhi to Mumbai", price: 4599, originalPrice: 6200, discount: 25, tag: "Hot Deal" },
  { id: "m2", category: "Hotels", name: "Taj Mahal Hotel, Mumbai", price: 12000, originalPrice: 15000, discount: 20, tag: "SBI Offer" },
  { id: "m3", category: "Electronics", name: "iPhone 15 Pro Max", price: 134900, originalPrice: 139900, discount: 4, tag: "EMI Available" },
  { id: "m4", category: "Shopping", name: "Flipkart Gift Voucher ₹5000", price: 4500, originalPrice: 5000, discount: 10, tag: "Cashback" },
  { id: "m5", category: "Travel", name: "IndiGo — Delhi to Goa", price: 3299, originalPrice: 4500, discount: 27, tag: "SBI ELITE" },
  { id: "m6", category: "Electronics", name: "Samsung 65\" QLED TV", price: 89990, originalPrice: 109990, discount: 18, tag: "No Cost EMI" },
];
